### ISSUE TITLE
Mono SDK missing and cannot starting 

### ISSUE THREAD

**Issue by LLNet** [flathub/com.jetbrains.Rider#3]
i have installed mono SDK and rider

![image](https://user-images.githubusercontent.com/7931918/80846982-544d3c00-8c0e-11ea-90fd-aab800a3cd95.png)

and when i try to run it.
![image](https://user-images.githubusercontent.com/7931918/80846841-e7d23d00-8c0d-11ea-879e-fe9057ae9271.png)

i thinking problem are here:
https://github.com/flathub/org.freedesktop.Sdk.Extension.mono5/blob/branch/19.08/org.freedesktop.Sdk.Extension.mono5.json#L50
and here:
https://github.com/flathub/com.jetbrains.Rider/blob/master/rider.sh#L10

**Comment by FakeShemp** [comment]
Solved with #4
