### ISSUE TITLE
Rider not building /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by ZagButNoZig** [flathub/com.jetbrains.Rider#43]
I configured rider to use my installed dotnet 6 [like this](https://github.com/flathub/com.jetbrains.Rider/issues/36#issuecomment-1017709947).

But since updating my local installed glibc from 2.33 to 2.35 I can not build anymore since I get this error : 
`  /var/run/host/usr/share/dotnet/dotnet: /usr/lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34 not found (required by /var/run/host/usr/share/dotnet/dotnet)`

I check and the snap install worked. 

What might be the issue here? I suspect its due to sandboxing as I have a similar error with intellij on flatpak.

@FakeShemp

**Comment by FakeShemp** [comment]
You can use the flathub version of dotnet6 with FLATPAK_ENABLE_SDK_EXT=dotnet6

**Comment by ZagButNoZig** [comment]
@FakeShemp 

Thanks for the quick reply. I'm not really sure where to put that.

`FLATPAK_ENABLE_SDK_EXT=dotnet6`

Could you give more precise instructions and I could maybe create a pull request to add that to the readme.

**Comment by FakeShemp** [comment]
You can install dotnet (and other sdks) with `flatpak install flathub org.freedesktop.Sdk.Extension.dotnet6`.

Then you can set the environment variable `FLATPAK_ENABLE_SDK_EXT` to `dotnet6` or `*` to enable one or all sdks.

A document explaining this should pop up at first time running the app but adding to Readme would be appreciated.

**Comment by ZagButNoZig** [comment]
Ok thanks. That fixes everything. I will open a PR for explanation.

**Comment by dginovker** [comment]
```
Which do you want to use (0 to abort)? [0-2]: 1
Similar refs found for ‘org.freedesktop.Sdk.Extension.dotnet6’ in remote ‘flathub’ (system):

   1) runtime/org.freedesktop.Sdk.Extension.dotnet6/x86_64/beta
   2) runtime/org.freedesktop.Sdk.Extension.dotnet6/x86_64/21.08
```

Which one should be selected/how will people in the future know the correct one?

**Comment by FakeShemp** [comment]
`flatpak info com.jetbrains.Rider`

It'll tell you the runtime and SDK.

**Comment by isaranghi** [comment]
How would you add new workloads, templates etc to those .net sdk extensions?

**Comment by FakeShemp** [comment]
The SDK repos are hosted on flathub. Dotnet 9 is here for instance https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet9
