### ISSUE TITLE
dotnet6 SDK extension on previous runtime version

### ISSUE THREAD

**Issue by andjons** [flathub/com.jetbrains.Rider#55]
Hi, I have .NET IDE RIder installed and SDK extension for dotnet6 (org.freedesktop.Sdk.Extension.dotnet6). Recently Rider was updated to use runtime version 22.08 and the IDE doesn't find the SDK anymore. I assume it's because the dotnet SDK extension is still on 21.08. Reverting Rider back to 4ec76cd71a4e3d7f8d8e7b873864d19b5b2b8f8024fd68bb4a595cb740d7bdcb from Flathub fixes the issue:

`$ sudo flatpak update --commit=4ec76cd71a4e3d7f8d8e7b873864d19b5b2b8f8024fd68bb4a595cb740d7bdcb com.jetbrains.Rider`

**Comment by FakeShemp** [comment]
It should be available now
