### ISSUE TITLE
.Net Core "Not Installed" on Steam Deck

### ISSUE THREAD

**Issue by shaunawins** [flathub/com.jetbrains.Rider#62]
I've installed Rider via Discover on Steam Deck and run the following two commands in an attempt to get it to create core apps, and it insists that Core is not installed. I've verified that the dotnet flatpaks are installed and I've even given Rider full filesystem access via flatseal.   
```
flatpak install flathub org.freedesktop.Sdk.Extension.dotnet6
flatpak install flathub org.freedesktop.Sdk.Extension.dotnet7
```
Any help would be appreciated.

**Comment by FakeShemp** [comment]
https://github.com/flathub/com.jetbrains.Rider/blob/master/README.md

**Comment by shaunawins** [comment]
> https://github.com/flathub/com.jetbrains.Rider/blob/master/README.md

Apparently environment variables set at the terminal do not apply systemwide on Steam Deck. I had to use flatseal to set the variable in question and now it's picking up dotnet7. 

Thank you for that, even though I thought I'd already done it.
